### ISSUE TITLE
 Fix Detection of characters around \Wordiables\ 

### ISSUE THREAD

**Issue by andrewvallejo** [andrewvallejo/lettra#3]
Find a way to separate punctuation from wordiables. 

## Current State

Typing "\1\" and "\1\" will turn red as they are both correct and match the current wordiables. 
The _issue_ is that my parser will allow "\1\,asd" and turn it red because it detects a wordiable but doesn't hard-check the syntax. This also applies to "asd\1\". Fortunately, other iterations of \1\ will change their color according.

## Todo

- [ ] If word is **"asd\1\"** then it should either
    - [ ] void that word as a wordiable
- [ ] If word is **"\1\asd"** then it should either
    - [ ] void that word as a wordiable 

## Notes

- today I learned that a word can become a wordiable if there are two `\` anywhere within the word. It should only become a wordiable if its `\` `word` `\`.
